spring:
  application:
    name: spring-security
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  app:
    jwt:
      secret: bXktc2VjcmV0LXNwcmluZy1ib290LWtleS1mb3ItdGhlLWRlbW8tc2VjdXJpdHktcHJvamVjdA==
      expiration-time: 100000
  web:
    resources:
      add-mappings: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/spring-security-with-authorization-server/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG
    org:
      springframework:
        security:
          web:
            access:
              intercept:
                FilterSecurityInterceptor: DEBUG

server:
  port: 9090

security:
  jwt:
    enabled: false